"""Type stubs for the Rust extension `ardiq._core`."""

from collections.abc import Awaitable, Callable
from typing import Any

Executor = Callable[[str, bytes, int, bool], Awaitable[tuple[int, bytes, int]]]

class ArdiqError(RuntimeError):
    """Base class for the errors ArdiQ's core raises."""

class BrokerError(ArdiqError):
    """Redis was unreachable, refused the connection, or dropped it."""

def init_logging(verbose: bool) -> None: ...

class ArdiqCore:
    def __init__(self, config: dict[str, Any]) -> None: ...
    @property
    def worker_id(self) -> str: ...
    @property
    def redis_url(self) -> str: ...
    @property
    def queue_name(self) -> str: ...
    @property
    def priorities(self) -> list[str]: ...
    @property
    def concurrency(self) -> int: ...
    @property
    def prefetch(self) -> int: ...
    @property
    def idle_timeout_ms(self) -> int: ...
    @property
    def poll_block_ms(self) -> int: ...
    @property
    def result_ttl_ms(self) -> int: ...
    burst: bool
    def enqueue(
        self,
        task_id: str,
        payload: bytes,
        priority: str | None = None,
        delay_ms: int = 0,
        schedule_ms: int = 0,
        expire_ms: int = 0,
        reset_result: bool = False,
    ) -> Awaitable[bool]: ...
    def enqueue_many(
        self,
        # (task_id, payload, priority, delay_ms, schedule_ms, expire_ms, reset_result)
        items: list[tuple[str, bytes, str | None, int, int, int, bool]],
    ) -> Awaitable[list[bool]]: ...
    def run(self, callback: Executor) -> Awaitable[None]: ...
    def stop(self) -> None: ...
    def queue_size(self) -> Awaitable[int]: ...
    def result(self, task_id: str) -> Awaitable[bytes | None]: ...  # core: no timeout
    def await_result(
        self, task_id: str, timeout_ms: int
    ) -> Awaitable[bytes | None]: ...
    def abort(self, task_id: str, result: bytes) -> Awaitable[bool]: ...
    def next_abort(self, timeout_ms: int) -> Awaitable[str | None]: ...
    def status(self, task_id: str) -> Awaitable[str]: ...
    def task_info(self, task_id: str) -> Awaitable[tuple[bytes | None, int, int]]: ...
