"""Type stubs for the Rust extension `ardiq._core`."""

from collections.abc import Awaitable, Callable
from typing import Any

Executor = Callable[[str, bytes, int], Awaitable[tuple[int, bytes, int]]]

def init_logging(verbose: bool) -> None: ...

class ArdiqCore:
    def __init__(self, config: dict[str, Any]) -> None: ...
    @property
    def worker_id(self) -> str: ...
    @property
    def redis_url(self) -> str: ...
    @property
    def queue_name(self) -> str: ...
    @property
    def priorities(self) -> list[str]: ...
    @property
    def concurrency(self) -> int: ...
    @property
    def prefetch(self) -> int: ...
    @property
    def idle_timeout_ms(self) -> int: ...
    @property
    def poll_block_ms(self) -> int: ...
    @property
    def result_ttl_ms(self) -> int: ...
    burst: bool
    def enqueue(
        self,
        task_id: str,
        payload: bytes,
        priority: str | None = None,
        delay_ms: int = 0,
        schedule_ms: int = 0,
        expire_ms: int = 0,
    ) -> Awaitable[bool]: ...
    def run(self, callback: Executor) -> Awaitable[None]: ...
    def stop(self) -> None: ...
    def queue_size(self) -> Awaitable[int]: ...
    def result(self, task_id: str) -> Awaitable[bytes | None]: ...  # core: no timeout
    def await_result(
        self, task_id: str, timeout_ms: int
    ) -> Awaitable[bytes | None]: ...
    def status(self, task_id: str) -> Awaitable[str]: ...
    def task_info(self, task_id: str) -> Awaitable[tuple[bytes | None, int, int]]: ...
